#!/bin/sh
# Set up Syncthing sync for ONE project on THIS machine (idempotent):
#   - compute the project's absolute path + the encoded Claude session-folder name
#   - create the code folder + session folder in Syncthing (matching IDs) with a .stignore
#   - write ~/.config/session-sync/config.sh and the .claude-sync marker
#   - if a peer Device ID is given, add it and share both folders with it (best-effort)
# Usage: cc-setup-sync <project-dir> [peer-device-id]
set -eu

SS_LIB="${SESSION_SYNC_LIB:-$(dirname "$0")/session-sync-lib.sh}"
[ -f "$SS_LIB" ] || SS_LIB="$HOME/.local/bin/session-sync-lib.sh"
# shellcheck disable=SC1090
. "$SS_LIB"

[ "$#" -ge 1 ] || die "usage: cc-setup-sync <project-dir> [peer-device-id]"
command -v syncthing >/dev/null 2>&1 || die "syncthing not found — run install-syncthing.sh first"
st_ready   # verify daemon reachable + API key

# --- derive paths/ids -------------------------------------------------------
PROJECT_DIR=$(cd "$1" 2>/dev/null && pwd) || die "project dir '$1' not found"
PEER="${2:-}"
NAME=$(basename "$PROJECT_DIR")
CODE_ID="${NAME}-code"
SESSION_ID="${NAME}-sessions"
# Claude encodes a project's session folder as its absolute path with every '/' -> '-'
ENC=$(printf '%s' "$PROJECT_DIR" | sed 's:/:-:g')
SESSION_DIR="$HOME/.claude/projects/$ENC"

echo "session-sync: project      $PROJECT_DIR"
echo "session-sync: code folder  id=$CODE_ID"
echo "session-sync: session dir  $SESSION_DIR"
echo "session-sync: session id   $SESSION_ID"

mkdir -p "$SESSION_DIR"

# --- .stignore (only create if missing; user may customize) -----------------
if [ ! -f "$PROJECT_DIR/.stignore" ]; then
  cat > "$PROJECT_DIR/.stignore" <<'EOF'
.venv
node_modules
target
__pycache__
*.pyc
dist
build
.DS_Store
*.log
.env
EOF
  echo "session-sync: wrote $PROJECT_DIR/.stignore"
fi

# --- register folders (idempotent) ------------------------------------------
folder_exists() { syncthing cli config folders list 2>/dev/null | grep -qx "$1"; }
add_folder() { # id path
  if folder_exists "$1"; then echo "session-sync: folder '$1' already registered"; return 0; fi
  syncthing cli config folders add --id "$1" --label "$1" --path "$2" \
    && echo "session-sync: added folder '$1'" || die "failed to add folder '$1'"
}
add_folder "$CODE_ID" "$PROJECT_DIR"
add_folder "$SESSION_ID" "$SESSION_DIR"

# --- config + marker --------------------------------------------------------
CFG_DIR="$HOME/.config/session-sync"; mkdir -p "$CFG_DIR"
cat > "$CFG_DIR/config.sh" <<EOF
# session-sync config (generated by cc-setup-sync on $(uname -sn))
PROJECT_DIR="$PROJECT_DIR"
CODE_FOLDER_ID="$CODE_ID"
SESSION_FOLDER_ID="$SESSION_ID"
PEER_DEVICE_ID="$PEER"
EOF
echo "session-sync: wrote $CFG_DIR/config.sh"
touch "$PROJECT_DIR/.claude-sync"
echo "session-sync: marked $PROJECT_DIR/.claude-sync"

# --- optional: pair + share with a peer device (best-effort) ----------------
if [ -n "$PEER" ]; then
  echo "session-sync: sharing with peer $PEER"
  syncthing cli config devices add --device-id "$PEER" --name peer 2>/dev/null \
    && echo "  added peer device" || echo "  peer device already present (or add skipped)"
  for f in "$CODE_ID" "$SESSION_ID"; do
    syncthing cli config folders "$f" devices add --device-id "$PEER" 2>/dev/null \
      && echo "  shared '$f' with peer" || echo "  '$f' already shared (or share skipped)"
  done
fi

MYID=$(st_get /rest/system/status | jq -r .myID)
cat <<EOF

session-sync: done for '$NAME'.
  This machine's Device ID: $MYID
  On the OTHER machine, clone the project to the same ~/… path, then run:
      cc-setup-sync <that-project-dir> $MYID
  Finally, accept the shared folders on each side (Syncthing UI or 'syncthing cli').
  Then use:  ccopen  to start, and  /handoff-close  to hand off.
EOF
